interface ZIF_I_21_CUSTOMERTP_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_21_CUSTOMERTP,
 CREATE_ZI_21_CUSTOMERTP        TYPE /BOBF/ACT_KEY VALUE '005056044E851EDD9093A23B261C8CE8',
 DELETE_ZI_21_CUSTOMERTP        TYPE /BOBF/ACT_KEY VALUE '005056044E851EDD9093A23B261D0CE8',
 LOCK_ZI_21_CUSTOMERTP          TYPE /BOBF/ACT_KEY VALUE '005056044E851EDD9093A23B261BCCE8',
 SAVE_ZI_21_CUSTOMERTP          TYPE /BOBF/ACT_KEY VALUE '005056044E851EDD9093A23B261D8CE8',
 UNLOCK_ZI_21_CUSTOMERTP        TYPE /BOBF/ACT_KEY VALUE '005056044E851EDD9093A23B261C0CE8',
 UPDATE_ZI_21_CUSTOMERTP        TYPE /BOBF/ACT_KEY VALUE '005056044E851EDD9093A23B261CCCE8',
 VALIDATE_ZI_21_CUSTOMERTP      TYPE /BOBF/ACT_KEY VALUE '005056044E851EDD9093A23B261D4CE8',
      END OF ZI_21_CUSTOMERTP,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_21_CUSTOMERTP,
        BEGIN OF LOCK_ZI_21_CUSTOMERTP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_21_CUSTOMERTP,
        BEGIN OF UNLOCK_ZI_21_CUSTOMERTP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_21_CUSTOMERTP,
      END OF ZI_21_CUSTOMERTP,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_21_CUSTOMERTP,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '005056044E851EDD9093A23B261E6CE8',
      END OF ZI_21_CUSTOMERTP,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_21_CUSTOMERTP,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDD9093A23B261BACE8',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDD9093A23B261B6CE8',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDD9093A23B261C6CE8',
      END OF ZI_21_CUSTOMERTP,
      BEGIN OF ZI_21_CUSTOMERTP_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDD9093A23B261DECE8',
      END OF ZI_21_CUSTOMERTP_LOCK,
      BEGIN OF ZI_21_CUSTOMERTP_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDD9093A23B261DCCE8',
      END OF ZI_21_CUSTOMERTP_MESSAGE,
      BEGIN OF ZI_21_CUSTOMERTP_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDD9093A23B261E0CE8',
      END OF ZI_21_CUSTOMERTP_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_21_CUSTOMERTP,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_21_CUSTOMERTP,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '005056044E851EDD9093A23B261ACCE8' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_21_CUSTOMERTP' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_21_CUSTOMERTP,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '005056044E851EDD9093A23B261E8CE8',
      END OF ZI_21_CUSTOMERTP,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZI_21_CUSTOMERTP               TYPE /BOBF/OBM_GROUP_KEY VALUE '005056044E851EDD9093A25F93F36CE9',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_21_CUSTOMERTP               TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EDD9093A23B261B0CE8',
 ZI_21_CUSTOMERTP_LOCK          TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EDD9093A23B261B8CE8',
 ZI_21_CUSTOMERTP_MESSAGE       TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EDD9093A23B261B4CE8',
 ZI_21_CUSTOMERTP_PROPERTY      TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EDD9093A23B261C4CE8',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_21_CUSTOMERTP,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  ID                             TYPE STRING VALUE 'ID',
  NAME                           TYPE STRING VALUE 'NAME',
  FORM                           TYPE STRING VALUE 'FORM',
  STREET                         TYPE STRING VALUE 'STREET',
  POSTBOX                        TYPE STRING VALUE 'POSTBOX',
  POSTCODE                       TYPE STRING VALUE 'POSTCODE',
  CITY                           TYPE STRING VALUE 'CITY',
  COUNTRY                        TYPE STRING VALUE 'COUNTRY',
  REGION                         TYPE STRING VALUE 'REGION',
  TELEPHONE                      TYPE STRING VALUE 'TELEPHONE',
  CUSTTYPE                       TYPE STRING VALUE 'CUSTTYPE',
  DISCOUNT                       TYPE STRING VALUE 'DISCOUNT',
  LANGU                          TYPE STRING VALUE 'LANGU',
  EMAIL                          TYPE STRING VALUE 'EMAIL',
  WEBUSER                        TYPE STRING VALUE 'WEBUSER',
      END OF ZI_21_CUSTOMERTP,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_21_CUSTOMERTP,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '005056044E851EDD9093A23B261B2CE8',
      END OF ZI_21_CUSTOMERTP,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZI_21_CUSTOMERTP,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE '005056044E851EDD9093A25F93EBACE9',
      END OF ZI_21_CUSTOMERTP,
    END OF SC_VALIDATION .
endinterface.
